version: '3.3'

services:
  registry:
    image: registry:2
    deploy:
      labels:
        primary: "true"
    volumes:
      - /registry/htpasswd:/auth_htpasswd
      - /registry/data:/var/lib/registry
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:80
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth_htpasswd
    ports:
      - "80"

